### ISSUE TITLE
Please provide instructions for users and developers

### ISSUE THREAD

**Issue by Giszmo** [prolic/futr#1]
I'd love to try it out but I'm not yet familiar with Haskell

**Comment by prolic** [comment]
Thanks for your interest @Giszmo.
Unfortunately you'd have to wait a couple of days, since I am currently heavily refactoring and the app doesn't work at the moment.

**Comment by prolic** [comment]
I'll keep you posted.

**Comment by prolic** [comment]
try this:

1. install stack (haskell build tool)
```bash
curl -sSL https://get.haskellstack.org/ | sh
```
2.  clone this repository
3. build and start
```bash
stack run
```

**Comment by Giszmo** [comment]
Hmm ... it does something for minutes but then errors out. On a second run, this is what I see on top:

```
$ stack run
nanovg           > configure
nanovg           > Configuring nanovg-0.8.0.0...
nanovg           > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The pkg-config package 'glew' is
nanovg           > required but it could not be found.
nanovg           > 
secp256k1-schnorr> configure                                        
secp256k1-schnorr> Configuring secp256k1-schnorr-0.0.1...           
secp256k1-schnorr> Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The pkg-config package
secp256k1-schnorr> 'libsecp256k1' is required but it could not be found.
secp256k1-schnorr>                                                  
```

**Comment by prolic** [comment]
```bash
git clone https://github.com/bitcoin-core/secp256k1
cd secp256k1
./autogen.sh
./configure --enable-module-schnorrsig --enable-module-extrakeys --enable-module-ecdh --enable-experimental
make
sudo make install
```

**Comment by Giszmo** [comment]
```
nanovg           > configure
nanovg           > Configuring nanovg-0.8.0.0...
nanovg           > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The pkg-config package 'glew' is
nanovg           > required but it could not be found.
nanovg           > 
```

remains

**Comment by prolic** [comment]
Hm, I don't know. Can you install it from your package manager?

**Comment by Giszmo** [comment]
Another day. Getting late here ...

**Comment by prolic** [comment]
Any success or no time so far?

**Comment by prolic** [comment]
Issue created here https://github.com/fjvallarino/monomer/issues/174

**Comment by prolic** [comment]
check https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md#libraries-sdl2-and-glew

**Comment by Giszmo** [comment]
Didn't try again. Sorry.

The ideal test is if you can run it in a standard docker container. That removes the hurdle of having to mess up my system to try something out and it gives you the assurance that the system is like the one you tried it on.

**Comment by prolic** [comment]
Yes sure, when I have time to get to it.

**Comment by prolic** [comment]
@fiatjaf you need to compile this from source yourself:

If you have it already installed, maybe you need to de-install it first, not sure.

```bash
git clone https://github.com/bitcoin-core/secp256k1
cd secp256k1
./autogen.sh
./configure --enable-module-schnorrsig --enable-module-extrakeys --enable-module-ecdh --enable-experimental
make
sudo make install
```

**Comment by prolic** [comment]
@fiatjaf @Giszmo please check https://github.com/prolic/futr/pull/3 and let me know if that works for you

**Comment by prolic** [comment]
At least for Linux this is done. I have no Mac, I leave this to someone else. I tried to compile it using Windows 10 in a VirtualBox, but ran into some issue with gcc on mingw64.
