### ISSUE TITLE
Unable to copy keys on backup page

### ISSUE THREAD

**Issue by carlcodling** [prolic/futr#11]
On the "Backup your keys" page I am able to highlight/select the keys but not copy them, neither with CTRL-C nor right click options, so in order to back them up I would need to manually type all the chars.

Using Plasma on Kubuntu 20.04

**Comment by prolic** [comment]
Thanks @carlcodling - will look into it asap.

**Comment by prolic** [comment]
Yes, I can confirm this is currently the case. I'm aware of this, but as I am reworking the UI completely at the moment, it doesn't make sense to address this issue now. You'll have to wait until the next release is ready to get pushed.
