### ISSUE TITLE
The client appImage v.0.0.2 starts off with "Waiting for relay connections to become available..."

### ISSUE THREAD

**Issue by xrviv** [prolic/futr#15]
> The client appImage v.0.0.2 starts off with "Waiting for relay connections to become available...
> Check your Internet connection or try to reconnect manually in the Relay Management. 

Prior to downloading the AppImage, I also had this error:

> WARNING: Could not find desktop file in AppDir, cannot create links for AppRun, desktop file and icon in AppDir root 
> appimagetool, continuous build (commit 729a1a6), build <local dev build> built on 2022-08-03 00:24:06 UTC
> WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
> Unable to guess the architecture of the AppDir source directory "futr.AppDir"
> A valid architecture with the ARCH environmental variable should be provided
> e.g. ARCH=x86_64 appimagetool ...

**Comment by prolic** [comment]
Those are just warnings and no errors, you can just ignore those.
Do you have any relays setup in the relay management?

**Comment by prolic** [comment]
Verify you have a `relays.ft` file next to your futr binary. The content should look like this:

```json
[{"uri":"ws://localhost:2700","info":{"writable":true,"readable":true}},{"uri":"wss://nostr.rocks","info":{"writable":true,"readable":true}}]
```

(Feel free to modify the list of relays of course.)

**Comment by xrviv** [comment]
Thanks will try to get back to this.

**Comment by prolic** [comment]
Feel free to reopen if you still encounter this problem.
